const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const User=require('../models/user.model');

//--------------------------------------------LOGIN--------------------------------------
const signIn = async (req,res)=> {
    
    const { email ,password }=req.body;
    
    try{
        //checking if user exists in our database
        const existingUser=await User.findOne({email});
        if(!existingUser)
        {
            return res.status(404).json({message:"User doesn't exists."})
        }

        //checking if password entered by user is correct
        const isPasswordCorrect= await bcrypt.compare(password,existingUser.password);
        if(!isPasswordCorrect)
        {
            return res.status(400).json({message:"Incorrect Password"})
        }

        //after above two checks a token can be created with id of user stored in token
        const token=jwt.sign
        (
            {id:existingUser._id},
            process.env.secret,
            {expiresIn:"1h"}
        )

        //returning token and user information
        res.status(200).json({result:existingUser,token})
    }
    
    catch(error){
        res.status(500).json({message:"Try Again Later"})
    }
} 

//-----------------------------------------REGISTER-----------------------------------------------


const signUp = async (req,res)=> {
    
    const { email ,password ,confirmPassword }=req.body;

    try{
        
        //checking if user exists in our database
        const existingUser=await User.findOne({email});
        if(existingUser)
        {
            return res.status(400).json({message:"User already exists."})
        }

        //checking if passwords match while registration
        if(password !== confirmPassword)
        {
            return res.status(400).json({message:"Passwords dont match"})
        }

        //hashing the password
        const hashedPassword= await bcrypt.hash(password,12)

        //saving new user in database
        const result=await User.create({email,password:hashedPassword})

        //creating token for current session
        const token=jwt.sign
        (
            {id:result._id},
            process.env.secret,
            {expiresIn:"1h"}
        )
        
        //returning token and user information
        res.status(200).json({result:result,token})


    }
    catch(error){
        res.status(500).json({error:error})
    }

} 

//-------------------------------CHECK IF TOKEN IS VALID-------------------------------------------------

const tokenIsValid = async (req, res) => {
    try {
        
        //extracting token from header
        const token = req.header('x-auth-token');
        if (!token) return res.json(false);
        
        //verifying if token is generated by us
        const verified = jwt.verify(token, process.env.secret);
        if (!verified) {
            return res.json(false);
        }
  
      return res.json(true);
    } 
    catch (error) {
      res.status(500).json({ message: error.message });
    }
  };
//-------------------------------------GETTING USER---------------------------------------------------

const getLoggedInUser = async (req, res) => {
    try {
        const user = await User.findById(req.user);
        res.json({
            id: user._id,
            username: user.username
        });
    } 
    catch (error) {
        res.status(500).json({ message: error.message });
    }
};


//-------------------------------------------EXPORTING FUNCTIONS---------------------------------------
exports.signIn = signIn;
exports.signUp = signUp;
exports.tokenIsValid = tokenIsValid;
exports.getLoggedInUser = getLoggedInUser;

